services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  web:
    build:
      context: .
      dockerfile: configuration/Dockerfile
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "${FLASK_PORT:-5000}:5000"

volumes:
  mongo_data:
